#!/usr/bin/env bash

[ -z "$PS1" ] && return


export FIATLUX_PATH=$HOME/fiatlux

export NVM_DIR="${HOME}/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# set 256 color profile where possible
# if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
#   export TERM=gnome-256color
# elif infocmp xterm-256color >/dev/null 2>&1; then
#   export TERM=xterm-256color
# fi
 

for dotfile in {bash_options,bash_exports,bash_aliases,bash_prompt}; do
  source ${FIATLUX_PATH}/dotfiles/$dotfile
done;

# Add tab completion for many Bash commands
if which brew > /dev/null && [ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]; then
  source "$(brew --prefix)/share/bash-completion/bash_completion";
fi;

# Add git completion
if which brew > /dev/null && [ -f "$(brew --prefix)/etc/bash_completion.d/git-completion.bash" ]; then
  source "$(brew --prefix)/etc/bash_completion.d/git-completion.bash";
fi;

# Add git flow completion
if which brew > /dev/null && [ -f "$(brew --prefix)/etc/bash_completion.d/git-flow-completion.bash" ]; then
  source "$(brew --prefix)/etc/bash_completion.d/git-flow-completion.bash";
fi;

# highlighting inside manpages and elsewhere
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

# homebrew completion
if  which brew > /dev/null; then
  source `brew --repository`/Library/Contributions/brew_bash_completion.sh
fi;

# Source github token if present
if [[ -f $HOME/.github_token ]]; then
  export GITHUB_TOKEN=$(cat $HOME/.github_token)
fi

