tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-drivers"
tap "adrianmihalko/ch340g-ch34g-ch34x-mac-os-x-driver", "https://github.com/adrianmihalko/ch340g-ch34g-ch34x-mac-os-x-driver.git"
tap "homebrew/cask-fonts" 
tap "schniz/tap"

cask_args appdir: "~/Applications"

# brew

brew "bash-completion@2"
brew "trash"
brew "tree"
brew "zsh-history-substring-search"
brew "unrar"

## git & co
brew "hub"
brew "ghi"
brew "git"

## Image & video
brew "exiftool"
brew "ffmpeg"
brew "imagemagick"
brew "youtube-dl"
brew "mkvtomp4"
brew "mkvdts2ac3"
brew "mkvtoolnix"

## Programming
brew "python"
brew "python3"
brew "pipenv"
brew "Schniz/tap/fnm"
brew "jq"
brew "yarn" 

## Code edit
brew "vim"
brew "neovim"

## React native
brew "watchman"

# Cask
cask "keepassx"
cask "docker"
cask "font-menlo-for-powerline"
cask "p4v"
cask "wch-ch34x-usb-serial-driver"

cask "qlcolorcode"
cask "qlmarkdown"
cask "quicklook-json"
cask "quicklook-csv"
cask "webpquicklook"
cask "betterzip"
cask "qsyncthingtray"

cask "imageoptim"
cask "image2icon"
cask "vlc"

cask "firefox"
cask "firefox-developer-edition"
cask "firefox-nightly"
cask "google-chrome"
cask "google-chrome-canary"
cask "opera"
cask "chromium"

cask "discord"
cask "dropbox"

cask "tunnelblick"
cask "sketch"
cask "arduino"
cask "patchwork"
cask "webtorrent"

cask "sourcetree"
cask "virtualbox"
cask "openscad"
cask "vscodium"
