set nocompatible
set encoding=utf-8

"
" Leader
"
let mapleader=","       " leader is comma

source ~/.vim/plugins.vim
source ~/.vim/settings.vim
source ~/.vim/mappings.vim
source ~/.vim/functions.vim

" autocmd Filetype gitcommit setlocal spell textwidth=72
" autocmd FileType markdown setlocal spell textwidth=80

" autocmd BufNewFile,BufRead *.md set ft=markdown
" let g:markdown_fenced_languages = ['css', 'javascript', 'js=javascript', 'json=javascript', 'xml', 'html']

"
" make python 2 and 3 work
"
let g:python2_host_prog = '/Users/lionel/.homebrew/bin/python2'
let g:python3_host_prog = '/Users/lionel/.homebrew/bin/python3'

" 
" Find
" --column: Show column number
" --line-number: Show line number
" --no-heading: Do not show file headings in results
" --fixed-strings: Search term as a literal string
" --ignore-case: Case insensitive search
" --no-ignore: Do not respect .gitignore, etc...
" --hidden: Search hidden files and folders
" --follow: Follow symlinks
" --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
" --color: Search color options

command! -bang -nargs=* Find call fzf#vim#grep('rg --column --line-number --no-heading --fixed-strings --ignore-case --no-ignore --hidden --follow --glob "!.git/*" --color "always" '.shellescape(<q-args>), 1, <bang>0)

