set nocompatible
set encoding=utf-8

"
" Leader
"
let mapleader=","       " leader is comma

source ~/.vim/plugins.vim
source ~/.vim/settings.vim
source ~/.vim/mappings.vim

" autocmd Filetype gitcommit setlocal spell textwidth=72
" autocmd FileType markdown setlocal spell textwidth=80

" autocmd BufNewFile,BufRead *.md set ft=markdown
" let g:markdown_fenced_languages = ['css', 'javascript', 'js=javascript', 'json=javascript', 'xml', 'html']



