#!/usr/bin/env zsh

[ -z "$PS1" ] && return
 
export FIATLUX_PATH=$HOME/fiatlux


for dotfile in {options,exports,aliases,prompt}; do
  source ${FIATLUX_PATH}/dotfiles/$dotfile
done;

# Add bash completion
for completion in git-completion.bash
do 
  if [ -r $(brew --prefix)/etc/bash_completion.d/$completion ]; then
    source $(brew --prefix)/etc/bash_completion.d/$completion
  fi
done

if [ -r $(brew --prefix)/etc/profile.d/bash_completion.sh ]; then
  source $(brew --prefix)/etc/profile.d/bash_completion.sh
fi

# highlighting inside manpages and elsewhere
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

# Source github token if present
if [[ -f $HOME/.github_token ]]; then
  export GITHUB_TOKEN=$(cat $HOME/.github_token)
fi


# FZF 
# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)

export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*, !.node_modules/*, !.bower_components/*"'
 

# fnm

eval "$(fnm env --multi --use-on-cd)"


ssh-add -K ~/.ssh/air_lumo
