#!/usr/bin/env bash

if ! type brew > /dev/null; then
  echo_title "installing brew & tools"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" 
  brew doctor
else
  echo "-- Updating brew"
  echo ""

  brew update
  brew upgrade
fi


# easy brewinstall function
function brewinstall() {
  brew install "${@}" 2> /dev/null
}

# Git & GihHub
brewinstall hub
brewinstall bash-completion
brewinstall git
brewinstall git-flow-avh

brewinstall tree
brewinstall exiftool
brewinstall ffmpeg --with-libass --with-fontconfig
brewinstall imagemagick --with-fontconfig
brewinstall youtube-dl
brewinstall mkvtomp4
brewinstall mkvdts2ac3
brewinstall mkvtoolnix

brewinstall python
brewinstall python3
brewinstall neovim
brewinstall oni

# React native
brewinstall watchman
brewinstall flow

brewinstall syncthing

brew cleanup
