#!/usr/bin/env bash

if ! type brew > /dev/null; then
  echo_title "installing brew & tools"
  mkdir $HOME/.homebrew && curl -L https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C $HOME/.homebrew
  export PATH=$HOME/.homebrew/bin:$HOME/.homebrew/sbin:$PATH
  
  brew doctor
else
  echo "-- Updating brew"
  echo ""

  brew update
  brew upgrade
fi

brew tap homebrew/dupes
brew tap homebrew/versions

# easy brewinstall function
function brewinstall() {
  brew install "${@}" 2> /dev/null
}

# Git & GihHub
brewinstall hub
brewinstall bash-completion
brewinstall git
brewinstall git-flow-avh

brewinstall tree
brewinstall exiftool
brewinstall ffmpeg --with-libass --with-fontconfig
brewinstall imagemagick --with-fontconfig
brewinstall youtube-dl
brewinstall mkvtomp4
brewinstall mkvdts2ac3
brewinstall mkvtoolnix

brewinstall python
brewinstall python3
brewinstall vim

# React native
brewinstall watchman
brewinstall flow

brewinstall syncthing

