#!/usr/bin/env bash


function caskinstall(){
  brew cask install "${@}" 2> /dev/null
}

brew cask upgrade

caskinstall font-menlo-for-powerline 
caskinstall p4merge

caskinstall qlprettypatch
caskinstall prefs-editor

caskinstall qlcolorcode
caskinstall qlmarkdown
caskinstall quicklook-json
caskinstall quicklook-csv
caskinstall webpquicklook
caskinstall android-file-transfer
caskinstall betterzip
caskinstall qsyncthingtray

caskinstall imageoptim
caskinstall image2icon
caskinstall vlc

caskinstall firefox
caskinstall firefox-developer-edition
caskinstall firefox-nightly
caskinstall google-chrome
caskinstall google-chrome-canary
caskinstall opera
caskinstall chromium

caskinstall slack
caskinstall discord 
caskinstall skype
caskinstall dropbox

caskinstall tunnelblick
caskinstall transmission 
caskinstall dash
caskinstall sketch
caskinstall mou
caskinstall todoist
caskinstall oni
caskinstall patchwork


caskinstall visual-studio-code
caskinstall sourcetree
caskinstall virtualbox
caskinstall openscad
 
cask cleanup
