#!/usr/bin/env bash


function caskinstall(){
  brew cask install "${@}" 2> /dev/null
}

brew cask upgrade

# Install formulae
brewinstall caskroom/cask/brew-cask

brew tap caskroom/cask
brew tap caskroom/fonts
brew tap caskroom/versions # Install beta versions

caskinstall font-menlo-for-powerline 
caskinstall p4merge

caskinstall qlprettypatch
caskinstall prefs-editor
caskinstall gifrocket

caskinstall qlcolorcode
caskinstall qlmarkdown
caskinstall quicklook-json
caskinstall quicklook-csv
caskinstall webpquicklook
caskinstall android-file-transfer
caskinstall betterzipql
caskinstall qsyncthingtray

caskinstall limechat
caskinstall imageoptim
caskinstall image2icon
caskinstall vlc
caskinstall acorn

caskinstall firefox
caskinstall firefoxdeveloperedition
caskinstall firefoxnightly
caskinstall google-chrome
caskinstall google-chrome-canary
caskinstall opera
caskinstall chromium 

caskinstall slack
caskinstall discord 
caskinstall skype
caskinstall dropbox

caskinstall tunnelblick
caskinstall transmission 
caskinstall dash
caskinstall sketch
caskinstall mou
caskinstall todoist
caskinstall oni
caskinstall patchwork


caskinstall visual-studio-code
caskinstall sourcetree
caskinstall virtualbox
caskinstall openscad
 
cask cleanup
