#!/usr/bin/env bash 

echo_subtitle "Installing Node.js"

fnm install 10
fnm use 10

if command -v node > /dev/null ; then
  echo_success "node installed"
else
  echo_fail "node not found"
fi  

# Installing global packages
yarn global add lionelb/subber
yarn global add cloc
yarn global add parker
yarn global add react-native-cli 
yarn global add expo-cli
yarn global add create-react-app 
yarn global add elm
yarn global add neovim

