#!/usr/bin/env bash 

echo_title "Installing Node.js"

curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.26.1/install.sh | bash

source $HOME/.nvm/nvm.sh
source $HOME/.bash_profile

if type -t nvm > /dev/null; then
  nvm install 0.12
  nvm install 5
  nvm install 6
  nvm alias default 6
  nvm use 6;
  echo_success "nvm & node installed"

else
  echo_fail "nvm not found"
fi  

# Installing global packages
npm install -g lionelb/subber
npm install -g cloc
npm install -g parker
npm install -g react-native-cli 
