#!/usr/bin/env bash 

echo_title "Installing Node.js"

curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

source $HOME/.nvm/nvm.sh
source $HOME/.bash_profile

if type -t nvm > /dev/null; then
  nvm install 6 
  nvm install node 
  nvm alias default node
  nvm use node
  echo_success "nvm & node installed"

else
  echo_fail "nvm not found"
fi  

# Installing global packages
npm -g install yarn
npm -g install lionelb/subber
npm -g install cloc
npm -g install parker
npm -g install react-native-cli 
npm -g install create-react-app
npm -g install elm

