#!/usr/bin/env bash

export COLOR_RED='\033[0;31m'
export COLOR_GREEN='\033[0;32m'
export COLOR_YELLOW='\033[0;33m'
export COLOR_BLUE='\033[0;34m'
export COLOR_CYAN='\033[0;36m'
export COLOR_RESET='\033[0m'
export COLOR_DIM='\033[2m'

export CHAR_OK=✔︎
export CHAR_ERR=✘
export CHAR_DONE=🎉
export CHAR_LIST=▸
export CHAR_TITLE=❯


function echo_title() {
   printf "${COLOR_BLUE}${CHAR_TITLE} ${COLOR_CYAN}$@ ${COLOR_RESET}\n"
}

function echo_subtitle() {
   printf "${COLOR_BLUE}  ${CHAR_TITLE} ${COLOR_CYAN}$@ ${COLOR_RESET}\n"
}
function echo_fail() {
   printf "${COLOR_RED}${CHAR_ERR} ${COLOR_RESET} $@\n"
}
function echo_info() {
   printf "${COLOR_YELLOW}${CHAR_LIST}${COLOR_RESET}${COLOR_DIM} $@\n"
}
function echo_success() {
   printf "${COLOR_GREEN}${CHAR_OK} ${COLOR_RESET} $@\n"
}


