#!/usr/bin/env zsh

function update_osx() {
  
  echo_title "osx preferences"

  for pref in $FIATLUX_PATH/osx/*.preference; do
    source $pref
  done

  killall -u $USER cfprefsd
  sleep 2 # wait for cfprefsd restart
  killall Dock Finder SystemUIServer NotificationCenter

  echo_success "osx preferences installed!"
}
