#!/usr/bin/env bash

#Export fiat_lux path
export FIATLUX_PATH=$HOME/fiatlux

FIATLUX_REPO="https://github.com/lionelb/fiatlux"

# Before relying on Homebrew, check that packages can be compiled
if ! type_exists 'gcc'; then
  e_error "The XCode Command Line Tools must be installed first."
  `xcode-select --install`
  exit 1
fi

if [ ! -d $FIATLUX_PATH/.git ]; then
  git clone $FIATLUX_REPO $FIATLUX_PATH
fi

if [ -d $FIATLUX_PATH/.git ]; then
  echo "fiat-lux have been cloned successfully"
  echo ""
  echo "Starting laptop configuration"

  export LAUNCHER_INSTALL=true

  source $FIATLUX_PATH/updater

  echo "Aborting  fiat-lux launcher"
fi

