#!/usr/bin/env zsh

#Export fiat_lux path
export FIATLUX_PATH=$HOME/fiatlux

FIATLUX_REPO="https://github.com/lionelb/fiatlux"

# Before relying on Homebrew, check that packages can be compiled
if ! xcode-select --print-path &> /dev/null; then

  # Prompt user to install the XCode Command Line Tools
  xcode-select --install &> /dev/null

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Wait until the XCode Command Line Tools are installed
  until xcode-select --print-path &> /dev/null; do
      sleep 5
  done

  print_result $? 'Install XCode Command Line Tools'

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Point the `xcode-select` developer directory to
  # the appropriate directory from within `Xcode.app`
  # https://github.com/alrra/dotfiles/issues/13

  sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
  print_result $? 'Make "xcode-select" developer directory point to Xcode'

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Prompt user to agree to the terms of the Xcode license
  # https://github.com/alrra/dotfiles/issues/10

  sudo xcodebuild -license
  print_result $? 'Agree with the XCode Command Line Tools licence'
fi

# install prezto
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

if [ ! -d $FIATLUX_PATH/.git ]; then
  git clone $FIATLUX_REPO $FIATLUX_PATH
fi

if [ -d $FIATLUX_PATH/.git ]; then
  echo "fiat-lux have been cloned successfully"
  echo ""
  echo "Starting laptop configuration"

  export LAUNCHER_INSTALL=true

  dotfiles()

  source $FIATLUX_PATH/updater
  
  setup_nvim()

  setup_node()

  setup_ruby()

  setup_python()

  echo_success "setup complete !"
fi

