#!/usr/bin/env zsh

echo_title "🔆  Fiat Lux!"
 
#setup install path
export FIATLUX_PATH=$HOME/fiatlux

# update prezto
zprezto-update

# update files from git
git -C $FIATLUX_PATH pull origin master
source $FIATLUX_PATH/dotfiles/.zshrc 

update_osx

brew upgrade

brew bundle check

brew bundle cleanup

printf "${CHAR_DONE}${COLOR_BLUE} your setup is complete.${COLOR_RESET}"

ext=$(code --list-extensions | xargs -L 1 echo code --install-extension)
