#!/usr/bin/env bash

#setup install path
export FIATLUX_PATH=$HOME/fiatlux

# update files from git
git -C $FIATLUX_PATH pull origin master

# Load all helpers functions
for file in $FIATLUX_PATH/functions/*; do
  source $file
done

echo_title " 🔆  Fiat Lux!"

# ask for admin privilege
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

source $FIATLUX_PATH/scripts/dotfiles
source $FIATLUX_PATH/scripts/recipes
source $FIATLUX_PATH/scripts/osx

echo -e " ${CHAR_DONE}${COLOR_BLUE} your setup is complete.${COLOR_RESET}"

