#!/usr/bin/env bash

#Export fiat_lux path
export FIATLUX_PATH=$HOME/fiatlux

FIATLUX_REPO="https://github.com/lionelb/fiatlux"

ask() {
  # http://djm.me/ask
  while true; do
    if [ "${2:-}" = "Y" ]; then
      prompt="Y/n"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="y/N"
      default=N
     else
      prompt="y/n"
      default=
    fi

    # Ask the question - use /dev/tty in case stdin is redirected from somewhere else
    read -p "$1 [$prompt] " REPLY </dev/tty

    #default
    if [ -z "$REPLY" ]; then
      REPLY=$default
    fi

    # Check if the reply is valid
    case "$REPLY" in
      Y*|y*) return 0 ;;
      N*|n*) return 1 ;;
    esac
  done
}

if ask "Should I install xcode ?" "N"; then
 echo "install xcode"
 `xcode-select --install`
fi

if [ ! -d $FIATLUX_PATH/.git ]; then
  git clone $FIATLUX_REPO $FIATLUX_PATH
fi

if [ -d $FIATLUX_PATH/.git ]; then
  echo "fiat-lux have been cloned successfully"
  echo ""
  echo "Starting laptop configuration"

  export LAUNCHER_INSTALL=true

  source $FIATLUX_PATH/scripts/updater
  # fiatlux-update()

  echo "Retrieving lumo configurator failed"
  echo "Aborting  fiat-lux launcher"
fi

