#!/usr/bin/env bash

echo_title  "Adding dev recipes"
source $FIATLUX_PATH/recipes/nvm

for recipe in $(ls $FIATLUX_PATH/recipes/ | grep -v nvm | sort -n); do
  source $FIATLUX_PATH/recipes/$recipe
done

echo_success "Recipes have been installed!"


